# Git Secret Scanner Configuration File

# LLM Configuration
llm:
  default_model: "gpt-5-mini"
  max_completion_tokens: 16384
  max_completion_tokens_message: 256
  system_prompt: "Find secrets. Return KEY : VALUE format only."
  system_prompt_commit: "You are a security expert. Extract and return ONLY actual secrets in KEY : VALUE format."

# Heuristic Configuration
heuristics:
  # Entropy thresholds
  entropy:
    threshold: 4.5
    min_entropy: 2.0
    low_entropy_cutoff: 2.5
    medium_entropy_cutoff: 3.0
    high_entropy_cutoff: 4.0
  
  # Confidence settings
  confidence:
    base_confidence: 0.3
    filter_threshold: 0.5
    
  # Confidence multipliers
  multipliers:
    dash_pattern: 0.2
    uppercase_underscore: 0.15
    lowercase_underscore: 0.2
    code_literal: 0.1
    low_entropy: 0.3
    medium_entropy: 0.5
    pem_marker: 0.1
    test_value: 0.2
    internal_test_pattern: 0.25
    comma_separated: 0.3
    space_heavy: 0.5
    very_low_entropy: 0.6
    high_entropy_boost: 1.2
    weak_pattern: 0.3
    known_pattern_boost: 1.3
    strong_keyword_boost: 1.1
    short_value: 0.7
    long_value: 0.8

# Secret detection patterns
patterns:
  # Regex patterns for secret detection - ORDER MATTERS, MORE SPECIFIC FIRST
  secret_patterns:
    # Most specific patterns first to avoid overlaps
    - pattern: "[\"']?([Aa][Uu][Tt][Hh])[_-]?([Tt][Oo][Kk][Ee][Nn])[\"']?\\s*[:=]\\s*[\"']([^\"']+)[\"']"
      type: "auth_token"
    - pattern: "[\"']?([Aa][Cc][Cc][Ee][Ss][Ss])[_-]?([Kk][Ee][Yy])[\"']?\\s*[:=]\\s*[\"']([^\"']+)[\"']"
      type: "access_key"
    - pattern: "[\"']?([Pp][Rr][Ii][Vv][Aa][Tt][Ee])[_-]?([Kk][Ee][Yy])[\"']?\\s*[:=]\\s*[\"']([^\"']+)[\"']"
      type: "private_key"
    - pattern: "[\"']?([Aa][Pp][Ii])[_-]?([Kk][Ee][Yy])[\"']?\\s*[:=]\\s*[\"']([^\"']+)[\"']"
      type: "api_key"
    - pattern: "[\"']?([Cc][Ll][Ii][Ee][Nn][Tt])[_-]?([Ss][Ee][Cc][Rr][Ee][Tt])[\"']?\\s*[:=]\\s*[\"']([^\"']+)[\"']"
      type: "client_secret"
    # More generic patterns last
    - pattern: "[\"']?([Pp][Aa][Ss][Ss][Ww][Oo][Rr][Dd])[\"']?\\s*[:=]\\s*[\"']([^\"']+)[\"']"
      type: "password"
    - pattern: "[\"']?(?![Aa][Uu][Tt][Hh]|[Aa][Cc][Cc][Ee][Ss][Ss])([Tt][Oo][Kk][Ee][Nn])[\"']?\\s*[:=]\\s*[\"']([^\"']+)[\"']"
      type: "token"
    - pattern: "[\"']?(?![Cc][Ll][Ii][Ee][Nn][Tt]|[Mm][Ee][Rr][Cc][Hh][Aa][Nn][Tt])([Ss][Ee][Cc][Rr][Ee][Tt])[\"']?\\s*[:=]\\s*[\"']([^\"']+)[\"']"
      type: "secret"
  
  # Known secret patterns for validation
  known_patterns:
    aws_access_key: '^AKIA[0-9A-Z]{16}$'
    github_token: '^(ghp_|gho_|ghu_|ghs_|ghr_)[a-zA-Z0-9]{36}$'
    jwt_token: '^eyJ[a-zA-Z0-9-_]+\.[a-zA-Z0-9-_]+\.[a-zA-Z0-9-_]+$'
    bearer_token: '^Bearer\s+[a-zA-Z0-9-._~+/]+=*$'
    slack_token: '^xox[baprs]-[0-9]{10,12}-[0-9]{10,12}-[a-zA-Z0-9]{24}$'

# Validation settings
validation:
  # Minimum secret length
  min_secret_length: 6
  
  # Maximum spaces in valid secret
  max_spaces: 5
  
  # Minimum keyword count for comma-separated false positives
  min_keyword_count_for_fp: 3
  
  # Keywords to check in comma-separated values
  comma_keywords:
    - "password"
    - "secret"
    - "token"
    - "key"
    - "api"
    - "auth"
    - "credential"
    - "private"
  
  # Minimum comma count for comma-separated check
  min_comma_count: 2
  
  # Internal patterns to check in values
  internal_patterns:
    - "_secret_"
    - "_test_"
    - "_demo_"
    - "_example_"
    - "_sample_"
  
  # Additional internal patterns 
  additional_patterns:
    - "super_"
  
  # Known prefixes for valid secrets
  known_prefixes:
    - "sk-"
    - "ghp_"
  
  # Token suffixes to check
  token_suffixes:
    - "_secret"
    - "_key"
    - "_token"
  
  # PEM markers prefixes
  pem_prefixes:
    - "-----BEGIN"
    - "-----END"
  
  # Thresholds for validation
  entropy_threshold_no_keyword: 3.5
  
  # Confidence return values
  confidence_return_comma: 0.2
  confidence_return_spaces: 0.3
  confidence_return_min: 0.4
  
  # Length thresholds
  min_length_short: 8
  max_length_long: 100
  
  # Space thresholds
  max_space_count: 3
  
  # Entropy thresholds for confidence
  entropy_very_low: 2.0
  entropy_high: 4.0
  
  # Test values to ignore
  test_values:
    - "password"
    - "secret"
    - "token"
    - "key"
    - "test"
    - "demo"
    - "example"
    - "sample"
    - "dummy"
    - "fake"
    - "placeholder"
    - "super_secret_value"
    - "secret_value"
    - "secret_key"
    - "your_password"
    - "your_password_here"
    - "my_password"
    - "the_password"
    - "your_secret"
    - "my_secret"
    - "the_secret"
    - "your_token"
    - "my_token"
    - "the_token"
    - "your_key"
    - "my_key"
    - "the_key"
    - "changeme"
  
  # Placeholder patterns
  placeholders:
    - "xxx"
    - "***"
    - "..."
    - "---"
    - "your_"
    - "my_"
    - "the_"
    - "todo"
    - "fixme"
    - "changeme"
    - "replace"
    - "update"
  
  # Weak patterns that reduce confidence
  weak_patterns:
    - "test"
    - "demo"
    - "example"
    - "sample"
    - "dummy"
    - "fake"
    - "placeholder"
  
  # Code literals to filter
  code_literals:
    - "secret"
    - "key"
    - "token"
    - "password"
    - "fallback"
    - "default"
    - "type"
    - "name"
  
  # Strong keywords that increase confidence
  strong_keywords:
    - "password"
    - "secret"
    - "token"
    - "key"
    - "api"
    - "auth"
    - "credential"
    - "access"
  
  # PEM certificate markers
  pem_markers:
    - "-----BEGIN RSA PRIVATE KEY-----"
    - "-----END RSA PRIVATE KEY-----"
    - "-----BEGIN PRIVATE KEY-----"
    - "-----END PRIVATE KEY-----"
    - "-----BEGIN PUBLIC KEY-----"
    - "-----END PUBLIC KEY-----"
    - "-----BEGIN CERTIFICATE-----"
    - "-----END CERTIFICATE-----"
    - "-----BEGIN RSA PUBLIC KEY-----"
    - "-----END RSA PUBLIC KEY-----"

# File filtering
file_filters:
  # File extensions to ignore
  ignore_extensions:
    - ".json"
    - "_test.json"
    - "_report.json"
  
  # File paths to ignore
  ignore_paths:
    - "output"
  
  # Specific filenames to ignore
  ignore_files:
    - "readme.md"
    - "readme.txt"
    - "readme.rst"
    - "readme"

# Scoring configuration
scoring:
  # Entropy score thresholds and values
  entropy_scores:
    - threshold: 4.5
      score: 0.35
    - threshold: 3.0
      score: 0.25
    - threshold: 2.0
      score: 0.15
    - threshold: 0.0
      score: 0.05
  
  # Length score thresholds and values
  length_scores:
    - min: 20
      max: 64
      score: 0.25
    - min: 12
      max: 19
      score: 0.20
    - min: 65
      max: 100
      score: 0.20
    - min: 8
      max: 11
      score: 0.15
    - min: 6
      max: 7
      score: 0.10
    - min: 0
      max: 5
      score: 0.05
  
  # Type scores based on key patterns
  type_scores:
    api_key: 0.23
    token: 0.22
    password: 0.20
    secret: 0.18
    default: 0.10
    known_pattern: 0.25
  
  # Complexity scores based on character types
  complexity_scores:
    all_types: 0.15    # uppercase, lowercase, digit, special
    three_types: 0.12
    two_types: 0.08
    one_type: 0.05

# CLI defaults
cli:
  default_output: "report.json"
  default_mode: "llm-fallback"
  default_repo: "."
